# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_add_irrigated_field_to_location_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year built'),
        ),
    ]
