# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ecoroofs.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_add_point_obscured_to_location_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', ecoroofs.models.UUIDPrimaryKeyField(default=uuid.uuid4, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', ecoroofs.models.UniqueDerivedSlugField(blank=True, editable=False, max_length=255)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Contractor'),
        ),
    ]
