# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_location_number_of_roofs'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='solar_over_ecoroof',
            field=models.NullBooleanField(),
        ),
    ]
