# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 23:50
from __future__ import unicode_literals

import datetime

from django.db import migrations


def forwards(apps, schema_editor):
    initial_date = datetime.datetime(month=10, day=1, year=2016)
    Location = apps.get_model('locations', 'Location')
    Location.objects.update(last_modified_on=initial_date)


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0018_location_add_last_modified_on'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
